### ISSUE TITLE
Libs for ndl_directmedia should be `NDL_directmedia`

### ISSUE THREAD

**Issue by mariotaku** [sundermann/webos-userland#4]
https://github.com/sundermann/webos-userland/blob/4baf7731e8b024a9c03d845a5cc127c2556fe148/share/pkgconfig/ndl_directmedia.pc#L10

Hi, I tried to use ndl_directmedia found by pkg-config, but getting errors in link time. And I think for `Libs` section it should be `NDL_directmedia` instead.

**Comment by sundermann** [comment]
Should be fixed in master
